#spring:
#  security:
#    user:
#      name: ${SECURITY_USER_NAME}
#      password: ${SECURITY_PASS_WORD}
#
#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB
#
#  datasource:
#    url: ${DB_URL}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: ${DB_USER_NAME}
#    password: ${DB_PASSWORD}
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        format_sql: true
#
#aws:
#  s3:
#    access-key: ${ACCESS_KEY}
#    secret-key: ${SECRET_KEY}
#    region: ap-northeast-2
#    bucket: ${BUCKET}
#
#server:
#  port: 8000
